package com.java.mybatis.idao;

import com.java.mybatis.domain.PublicMethod;
import com.java.mybatis.domain.PublicMethodExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PublicMethodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_method
     *
     * @mbg.generated Sun Feb 11 18:24:59 CST 2018
     */
    long countByExample(PublicMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_method
     *
     * @mbg.generated Sun Feb 11 18:24:59 CST 2018
     */
    int deleteByExample(PublicMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_method
     *
     * @mbg.generated Sun Feb 11 18:24:59 CST 2018
     */
    int deleteByPrimaryKey(String methodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_method
     *
     * @mbg.generated Sun Feb 11 18:24:59 CST 2018
     */
    int insert(PublicMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_method
     *
     * @mbg.generated Sun Feb 11 18:24:59 CST 2018
     */
    int insertSelective(PublicMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_method
     *
     * @mbg.generated Sun Feb 11 18:24:59 CST 2018
     */
    List<PublicMethod> selectByExampleWithBLOBs(PublicMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_method
     *
     * @mbg.generated Sun Feb 11 18:24:59 CST 2018
     */
    List<PublicMethod> selectByExample(PublicMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_method
     *
     * @mbg.generated Sun Feb 11 18:24:59 CST 2018
     */
    PublicMethod selectByPrimaryKey(String methodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_method
     *
     * @mbg.generated Sun Feb 11 18:24:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") PublicMethod record, @Param("example") PublicMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_method
     *
     * @mbg.generated Sun Feb 11 18:24:59 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") PublicMethod record, @Param("example") PublicMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_method
     *
     * @mbg.generated Sun Feb 11 18:24:59 CST 2018
     */
    int updateByExample(@Param("record") PublicMethod record, @Param("example") PublicMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_method
     *
     * @mbg.generated Sun Feb 11 18:24:59 CST 2018
     */
    int updateByPrimaryKeySelective(PublicMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_method
     *
     * @mbg.generated Sun Feb 11 18:24:59 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(PublicMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_method
     *
     * @mbg.generated Sun Feb 11 18:24:59 CST 2018
     */
    int updateByPrimaryKey(PublicMethod record);
}