package mybatis.idao;

import java.util.List;
import mybatis.domain.PrivateMethod;
import mybatis.domain.PrivateMethodExample;
import org.apache.ibatis.annotations.Param;

public interface PrivateMethodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_method
     *
     * @mbg.generated Sun Mar 25 10:46:26 CST 2018
     */
    long countByExample(PrivateMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_method
     *
     * @mbg.generated Sun Mar 25 10:46:26 CST 2018
     */
    int deleteByExample(PrivateMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_method
     *
     * @mbg.generated Sun Mar 25 10:46:26 CST 2018
     */
    int deleteByPrimaryKey(String methodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_method
     *
     * @mbg.generated Sun Mar 25 10:46:26 CST 2018
     */
    int insert(PrivateMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_method
     *
     * @mbg.generated Sun Mar 25 10:46:26 CST 2018
     */
    int insertSelective(PrivateMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_method
     *
     * @mbg.generated Sun Mar 25 10:46:26 CST 2018
     */
    List<PrivateMethod> selectByExampleWithBLOBs(PrivateMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_method
     *
     * @mbg.generated Sun Mar 25 10:46:26 CST 2018
     */
    List<PrivateMethod> selectByExample(PrivateMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_method
     *
     * @mbg.generated Sun Mar 25 10:46:26 CST 2018
     */
    PrivateMethod selectByPrimaryKey(String methodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_method
     *
     * @mbg.generated Sun Mar 25 10:46:26 CST 2018
     */
    int updateByExampleSelective(@Param("record") PrivateMethod record, @Param("example") PrivateMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_method
     *
     * @mbg.generated Sun Mar 25 10:46:26 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") PrivateMethod record, @Param("example") PrivateMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_method
     *
     * @mbg.generated Sun Mar 25 10:46:26 CST 2018
     */
    int updateByExample(@Param("record") PrivateMethod record, @Param("example") PrivateMethodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_method
     *
     * @mbg.generated Sun Mar 25 10:46:26 CST 2018
     */
    int updateByPrimaryKeySelective(PrivateMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_method
     *
     * @mbg.generated Sun Mar 25 10:46:26 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(PrivateMethod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_method
     *
     * @mbg.generated Sun Mar 25 10:46:26 CST 2018
     */
    int updateByPrimaryKey(PrivateMethod record);
}